ASPP/pelita

.travis.yml
This makes travis use a container instead of a fuller VM.
=> BLD: Speedup travis runs by not needing sudo rights.

check_boilerplate.sh, pelita/__init__.py, pelita/__version_from_git.py, pelita/containers.py, pelita/datamodel.py, pelita/game_master.py, pelita/graph.py, pelita/layout.py, pelita/messaging/json_convert.py, pelita/player.py, pelita/simplesetup.py, pelita/utils/__init__.py, pelita/utils/debug.py, pelita/utils/threading_helpers.py, pelita/viewer.py
I have no idea if this is actually useful. Let’s get rid of it.
=> DOC: Remove the __docformat__ specification.

contrib/ci.cfg, contrib/ci_engine.py
We can now specify
* = players/*
in the config and have all teams (which may be symlinks)
in the players folder automatically imported.
=> NF: Allow for wildcard teams

pelita/libpelita.py
`../path-to-script` needs to accept a zmq.PAIR connection as a first argument.
=> NF: bin@../path-to-script runs generic code as a pelita client.

pelita/libpelita.py, pelita/simplesetup.py, pelitagame, tournament/komode.py, tournament/roundrobin.py, tournament/test_tournament.py, tournament/tournament.py, tournament/tournament.yaml
New, more flexible tournament mode. To be rebased when #304 is merged.
Configuration is done in a yaml file.
location: Munich
date: 2015
team_prefix: group
seed: 42
bonusmatch: True
teams:
- spec: FoodEatingPlayer
members:
- "Player One"
- "Player Two"
- spec: StoppingPlayer
members:
- "b"
- spec: random
members:
- noone
`spec` is the same module specifier that the pelitagame command line uses. So, things like `py3@/home/user/pelita_player:dumb_factory` are also possible. The name of the team will be queried during initialisation of the tournament (which also serves as a short sanity check).
Still TODO:
=> Flexible tournament

pelita/containers.py, pelita/game_master.py, test/test_containers.py
=> ENH: Use KeyError on Mesh container to have proper get() available.

pelita/ui/tk_sprites.py
=> BF: Small geometry should not divide by zero.

pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, pelita/simplesetup.py, pelita/utils/__init__.py, test/test_pelitagame.py
(On top of the setup.py changes, sorry.)
A call to
remote# pelita_player --remote players/SmartRandomPlayer.py tcp://0.0.0.0:12345
binds the given zmq socket and waits for incoming match requests. For each request it opens a subshell which connects to the local game master and plays the game.
Local players can then play against the networked player with
local# pelita my_player remote:tcp://server:12345
Current problems:
* local does not know its IP address, therefore remote does not know how to connect to the local game master. This may either be given by the local user (straight forward to implement but won’t work with firewalls then) or the whole setup has to be restructured to use zmq addresses (this means we will have to reuse the sockets, I think).
Do not merge yet but it is better …
=> Proof of concept for network players.

pelita/game_master.py, test/test_game_master.py
Fixes #418. I know that we were burnt by this, so I thought I would address it...
This just checks that a layout includes food and, if not, gives a warning. I've put the warning in the factory method that creates the layout rather than in the GameMaster - I don't know what you'd prefer. Since there are several tests with no food, I've also added a pytest.ini to suppress the warnings from them and keep the output cleaner (I couldn't see any other customisation for py.test already in the repository).
Edit: Just saw the format for marking commits, sorry!
Edit2: Failing on 3.3 seems strange, although I see that configuration uses a different pytest version (2.9.2 vs 3.x in later ones). I don't see anything about how warnings are handled in the changelog, though.
=> Give warning if creating layout without food (fixes #418)

.travis.yml, pelita/libpelita.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, pelita/simplesetup.py, pelita/tournament/tournament.py, test/test_libpelita.py, test/test_pelitagame.py, test/test_tournament.py
Replaces #386.
This moves the run_match logic from the tournament to libpelita. Currently this spawns a new subprocess with the given command line arguments and captures the final state as well as stdout, stderr. This might make it thread-safe, although there are no tests for this yet.
The disadvantage is the slightly awkward work-arounds that go with running an external process and having basically no feed-back while the function is running.
=> Make a complete game of pelita executable from libpelita

pelita/scripts/pelita_player.py, test/test_pelita_player.py, test/test_pelitagame.py
Previously, our check_module function would take a guess at what a proper module would look like and fail if it looked differently.  We now relax some of the constraints and just try to import the module (with importlib). If it works, good, if it doesn’t, then we can still fail.
As a side-effect, this change allows to specify a module without path delimiters (unless it would collide with a built-in player) and modules containing only .pyc files.
Unfortunately, this still imports the modules into the global namespace, which means that in the tests, we have to use a new module name in each one (otherwise there will be collisions).
For reference, I also tried the following logic with `importlib` (where we could get more explicit feedback about which modules are imported – and potentially …
=> Rework the import logic in pelita_player

demo/demo_team.py, pelita/player/__init__.py, pelita/player/player_functions.py, pelita/player/team.py, test/test_team.py
The general idea is that we give up on the object oriented interface and instead have the user supply a move function (or perhaps several for the individual bots) that receives a universe/state and a storage dict.
The universe/state object should contain all necessary information to evaluate a state. The representation will be kept as simple as possible (a simple print should show all available information to help with observability) and we will export all the previous helper methods on AbstractPlayer as functions.
Additionally, we initialise an empty storage dict which we pass to the move function. The storage dict can be used to share data between the individual players and rounds and is persistent for a whole game.
The goal will be to get to an immutable universe/game_state …
=> ENH: New approach for the simplified player API.

pelita/scripts/pelita_main.py
Small improvement for the pelita cli help that should make it a little easier to ignore the advanced settings.
From this
Options:
--help, -h            show this help message and exit
--version             show the version number and exit
--log [LOGFILE]       print debugging log information to LOGFILE (default
'stderr')
--dump [DUMPFILE]     print game dumps to file (will be overwritten)
DUMPFILE (default 'pelita.dump')
--replay [DUMPFILE]   replay a dumped game DUMPFILE (default 'pelita.dump')
--rounds ROUNDS       maximum number of rounds to play
--fps FPS             (approximate) number of frames per second in a
graphical viewer
--seed SEED           fix random seed
--geometry NxM        initial size of the game window
--dry-run             load players but do not actually play the …
=> Rearranged CLI --help

pelita/libpelita.py
This means Tk will not be automatically closed when the main process exits.
Lacks proper testing on Windows, so do not merge yet. The PR is mostly for reference and as a quick fix for #451 (mostly to allow for playing proper tournaments again. see: #456).
A better solution would explicitly have the supervising process take control of Tk (for example by running the viewer manually before starting the game). For the tournament this could also become an improvement: Having one Tk window for all the games that never closes.
=> BF: Decouples the Tk process from its calling process.

pelita/game_master.py, test/test_game_master.py
It has been told (wrongly) in the presentation for ages but since it is easier to change code than to update a line in the presentation, we’ll now make it right.
Previously, the game would still finish the current round, even though all food had been eaten by one of the players (or both players).
The new rule will arguably be an even bigger advantage for the starting team but on the other hand it will also simplify the code for all parties since now the assertion
assert len(food) > 0
is always true (for food ∈  {team_food, enemy_food}).
=> [RULE CHANGE] End the game immediately once all food for a team has been eaten.

pelita/graph.py
Given that moving Graph to be its own class (right thing to do) requires
some work at the moment, we make it a subclass of UserDict, so that at
least we can properly implement `__copy__` This is needed because
the default `dict.copy()` behaviour is shortcutting `__copy__`.
Anyway, this mess needs to be cleaned up and Graph should be its own
thing.
=> Make Graph a subclass of Userdict

pelita/ui/tk_canvas.py
Python’s time is either inexact on Windows or Pelita is just super fast there …
=> BF: Catch ZeroDivisionError in fps calculation.

pelita/utils/__init__.py, test/test_team.py
To avoid confusion there should be only one way to pass the layout to `setup_test_game`. It's easiest to pass this always as a string and add the `food`, `bots`, `enemy` parameter as arguments to `setup_test_game`.
=> Layout passed to setup_test_game should always be a string

pelita/tournament/tournament.py
=> ENH: Do not print output for flite.

pelita/viewer.py
Fixes #518 .
When the tournament runs a game, it will bind a `zmq.PAIR` and then `Popen` a call to `pelita` with the URI of the socket. Once the game has finished, `pelita` will send the result on the socket and once the tournament has read the result, it will send a SIGTERM to `pelita`. This may result in files not being properly written.
The flush should fix the problem. (The result is only sent *after* the dump has been written.)
Two improvements are possible:
1. Make the `zmq.PAIR` bidirectional and tell `pelita` to properly shut down via this channel.
2. Write the dump file in the tournament and not in `pelita`. (The `zmq.PAIR` sends all dump data anyway.)
=> BF: Flush the pelita.dump after writing.

pelita/libpelita.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, pelita/scripts/pelita_tkviewer.py, pelita/scripts/pelita_tournament.py, pelita/simplesetup.py, pelita/tournament/tournament.py, pelita/ui/tk_canvas.py, pelita/ui/tk_utils.py, pelita/ui/tk_viewer.py
Use `logging.getLogger(__name__)` everywhere.
=> ENH: Clean up the logging a little.

pelita/player/team.py, pelita/utils/__init__.py, test/test_team.py
state is now an extra argument to the move function. In order to
properly update state, the move function now must return both the
move tuple and an updated state.:
move(bot, state) -> (move, state)
Additionally, `move` receives a `Bot` instance of the current bot which is equivalent to the previous `game.team[turn]`.
Concept branch for #520 which requires additions (and discussions?) in https://github.com/ASPP/pelita_template before we should merge it. (Should we manually update the 2018 players so that they still run for tests or provide a compatibility mode?)
=> ENH: Make state explicit in move

pelita/game_master.py, pelita/libpelita.py, pelita/scripts/pelita_main.py, pelita/simplesetup.py
Adds a `--long-help` flag to `pelita`.
The implementation is a slight hack because the feature does not exist in argparse. It uses a helper function `long_help` that will be `argparse.SUPPRESS` when `--long-help` is not set so that it will usually hide the advanced features from normal users.
Additionally, this commit does some cleaning up and gets rid of the `initial_delay` variable.
=> Add --long-help

pelita/libpelita.py, pelita/scripts/pelita_main.py, pelita/tournament/tournament.py
Quick fix for #519
Stdout and stderr are captured in `call_pelita` but are just written to a variable that is then returned by `call_pelita`. So far, the tournament script would only present the stdout and stderr to the user, if `call_pelita` itself did not return a meaningful result. In the case of a player crashing, this would just trigger a normal disconnect and the other team would simply win, so it was never considered to be a situation where the tournament host would need to investigate.
This adds a fix to the tournament that will store stdout and stderr of `call_pelita` directly in a file, *after* `call_pelita` has run.
We could additionally add the feature that `call_pelita` writes directly to a file (or log), if requested, but unless we need live updates (`tail -f`), this fix …
=> ENH: Store the tournament output next to the dumpfile.

.travis.yml, build-docs.sh, make-doc-tree.sh
Even though I think we did a nice job with our `commit-doc-tree.sh` script and exploited some nice low-level git features there, the automatic updating of the pelita website has been broken for quite a while now and travis would not inform us what went wrong.
This PR uses the travis deploy mechanism to automatically publish our generated docs.
(This PR comes with a companion PR #540 that does the same thing but uses travis stages.)
=> Use the travis deploy mechanism to publish our docs to gh-pages

pelita/libpelita.py, pelita/tournament/tournament.py, test/test_libpelita.py, test/test_tournament.py
The subprocess in `call_pelita` now uses temporary files instead of pipes for stdout/stderr, which did not work on Windows.
=> Make tournament work on Windows.

pelita/libpelita.py, pelita/scripts/pelita_main.py, pelita/simplesetup.py
This PR makes a few API changes to the `libpelita.run_game` function, eliminating the need to pass a `game_config` dict in favour of explicit arguments (with sensible defaults). This should make it easier to use `run_game` in bulk testing similar to the following snippet:
for enemy in ["enemy_players/team1", "enemy_players/team2"]:
layout = get_layout() # ...
game_state = run_game([my_move, enemy], rounds=300, layout=layout)
Additionally, the team arguments to `run_game` may now be either team spec strings (as one would use on the pelita command line and which run in a subprocess) as well as plain `move(bot, state)` functions which will run in the same process and therefore allow for debugging (there is no timeout by design) and profiling.
A simple script for profiling might look as …
=> Add same-process mode to run_game that allows for easier debugging and profiling

pelita/layout.py
it does not help to use the context manager for the StringIO object.
By removing it we save one level of indentation, which makes the code more
readable. The diff looks crazy because git has problems understanding that
the code has been simply dedented by one level of indentation, but indeed
no code has been altered apart from the first line of the diff where the
"with StringIO..." was.
=> Remove StringIO context manager

pelita/layout.py, pelita/scripts/pelita_main.py, test/test_layout.py
This removes `layout.load_layout` because it is at best unneeded and at worst confusing because of its mutually exclusive call interface (and also because it would only return a string of a layout and not automatically parse it).
If one wants to load an internal layout (from `__layouts.py`) one should use `get_layout_by_name` directly. If one wants to load a layout from a file, reading the file with `pathlib.Path` serves the same purpose.
=> RF: Remove ambiguous load_layout function.

pelita/layout.py, pelita/scripts/pelita_main.py, test/test_game.py, test/test_layout.py
`load_layout(layout_file=FILE)` can be replaced with `Path(FILE).read_text()`.
`load_layout(layout_name=NAME)` can be replaced with `get_layout_by_name(NAME)`.
=> Remove load_layout function from Layout and fix test_game

test/test_game.py
Instead of repeating a test blindly for n times, we generate the layouts directly in the parametrisation and add them as arguments to the test function. This means, the layout name will be printed in case of failure.
=> TST/RF: Remove the seedval and parametrize random tests.

pelita/game.py, pelita/player/team.py, test/test_game.py
This adds a minimal working version of `run_game` (only for local move functions currently). The interface of `prepare_bot_state` and `prepare_viewer_state` still has to be defined properly (with regards of serialisation).
Additionally, the third commit adds a (Python 3.7 only) dataclass for the GameState, which currently serves as a normative description of what we allow in our internal game_state dict.
We might, however, decide that dataclasses (arguably, we could do the same thing with a normal class as the serialisation is done in the specialised functions `prepare_bot_state` anyway) are not such a bad idea after all, and use it to its full potential. (Replacing `game_state['food']` → `game_state.food` and the notorious `max(game_state['walls'])[0]` → `game_state.width`.)
=> Minimal working version of run_game

pelita/game.py, pelita/gamestate_filters.py, test/test_filter_gamestates.py
Please don’t merge yet. But please don’t work on the noiser functions either. ;)
The plan is to do the noising inside the `prepare_bot_state` function,
which takes a complete game_state and shapes it into a form that can be
sent to a player. This means, we don’t have to rely on the whole
game_state here but can simply use the current bot’s position and a list
of enemy bots that can potentially be noised.
Also, I removed the tabs.
=> WIP: Changed API for noiser

pelita/game.py, pelita/player/team.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, pelita/simplesetup.py, test/demo01_stopping.py, test/demo02_random.py, test/test_game.py
Given the methods in `game.py`, a `RemoteTeam` behaves just as a `Team` class (it is generated with `make_team` but takes a string instead of a `move` method) such as `set_initial` and `get_move`). Underneath however, it starts a subprocess of `pelita-player` with the `team_spec` as an argument.
When the class is cleaned up, the `__del__` method is (hopefully) called, which will then terminate the subprocesses (in case this hasn’t happened yet).
NB: This means that test games that run a few rounds of `play_turn`, then store the `game_state` in a list for example and then start a new game for a few rounds etc. will have dozens or more of still-running `pelita-player` processes around, since the teams are saved inside `game_state` and will therefore not be garbage collected. We might want …
=> Add RemoteTeam class

pelita/game.py, pelita/scripts/pelita_main.py, test/test_game.py
The logic is as follows:
run_game is basically a loop with the following conventions:
def run_game(**game_kwargs):
game_state = setup_game(**game_kwargs)
assert game_state['round'] == None
assert game_state['turn'] == None
while not game_state['gameover']:
game_state = play_turn(game_state)
assert game_state['round'] >= 0
assert game_state['round'] < game_state['max_rounds']
assert 0 <= game_state['turn'] < 4
The round and turn in a `game_state` _in this loop_ will always signify the bot that has last moved. If no bot has moved yet, these are naturally `None`. The same state will be given to the viewers (this happens inside `play_turn`) to avoid confusion. A function `check_final_move` is added to properly check whether another move can be played or whether we are in the last turn of the …
=> Improving the logic of the round and turn handling

pelita/exceptions.py, pelita/game.py, pelita/network.py, pelita/player/team.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, pelita/scripts/pelita_tkviewer.py, pelita/simplesetup.py, pelita/ui/tk_canvas.py, pelita/ui/tk_sprites.py, pelita/ui/tk_viewer.py, pelita/viewer.py
This PR changes the Tk viewer to run with a (still unoptimised) `game_state` and gets rid of all the old datamodel/universe API. Not all features are ported yet and there may be silent failures for some of the changed keys in `game_state`. Also, there is an UI bug (on OS X at least) where the maze loses some of its elements during the game. It is yet unclear to me why this is.
Additionally, viewers are now initialised in `run_game` (or rather `setup_game`). To ensure that the viewer can properly control the running game (and also ensure that the game waits until the viewer is ready) and exit it correctly, some minimal control code has been added to the loop in `run_game`. It is our aim to keep this control code and the loop as simple as possible, so that users can build their own game …
=> Adapt the Tk viewer to the new API and add it to run_game

pelita/player/team.py
before this, homezones were instantiated as empty.
=> fix homezone creation bug:

pelita/graph.py, test/test_graph.py
Having oneself as a neighbour is consistent with legal_positions and has
been that way in the tests too.
=> BF/TST: Add own position as neighbour in graph and update tests to new API

pelita/utils/__init__.py
`setup_test_game` would not set Bot.random anymore. This needs to be fixed a little more thoroughly at a later point.
=> BF: Fix for Bot.random in setup_test_game

pelita/libpelita.py, pelita/tournament/tournament.py, test/test_filter_gamestates.py, test/test_libpelita.py, test/test_tournament.py
Tournament tests rely on #590 to be merged. Otherwise the players won’t work.
=> Fixes in call_pelita (parsing of the reply-to dict) and tournament

contrib/ci_engine.py
Previously, it had only been possible to use module-based players in the ci-engine, as the ci-engine would hash the directory contents and re-init a player when the data had changed. Naturally very useful for continuous integration.
The engine has now been adapted for scripts (as the new API prefers): When a script is specified, we use the `modulefinder` to give us a list of all modules that this script loads (recursively) and we use this list as our hash. (We only look at the modules that have a path relative to our script.)
=> Adapt ci-engine for pelita scripts

pelita/gamestate_filters.py, test/test_filter_gamestates.py, test/test_game_master.py
Interestingly, there was a position missing from the list of expected
positions in test_uniform_noise_4_bots_manhattan. Either the old
algorithm had an error or the new one still has.
=> BF/TST: Fix bug in noiser and adapt old tests

pelita/game.py, pelita/layout.py, test/test_game.py, test/test_game_master.py, test/test_layout.py, test/test_players.py, test/test_remote_game.py
There is only one error per (round, turn) allowed and all lead to the
same outcome -> a random move. Mirroring this in the data structure
simplifies the checks.
Currently, the turn is in range(0, 3), ie. global, even though
the error state is split between the two teams and therefore we could
also use the team-internal turn.
Additionally, this fixes the double-error problem when a timeout occurred
and a user would get an additional error for making a wrong move.
Fixes #600.
=> RF: Change game_state['error'] to list of dicts.

pelita/game.py, pelita/player/team.py, pelita/scripts/pelita_player.py, pelita/simplesetup.py, test/test_pelita_player.py, test/test_remote_game.py
Closes #598. Further refactoring of RemoteTeam/ZMQConnection will come in later PRs.
This PR also removes old-style factory-based loading `def team` and fixes a bug where a belated message from a client would lead to a newer message being ignored (thus giving a second time out).
=> Fix timeout handling in RemoteTeam

pelita/game.py, pelita/simplesetup.py, pelita/ui/tk_canvas.py, pelita/viewer.py
`(round, turn)` cannot be used as a key in json but it is a good thing anyway not to send all the information that the viewer already knows about (especially in the case of past errors it is rather special interest anyway).
Future code may exclude the walls from serialisation too, at least when sending them to the zmq viewers (for local viewers there is not much harm in keeping them in the dict).
Closes #603.
=> Only send the current error to the viewers

contrib/ci_engine.py, pelita/game.py, pelita/libpelita.py, pelita/player/team.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, pelita/scripts/pelita_tournament.py, pelita/tournament/tournament.py, pelita/viewer.py, test/test_libpelita.py, test/test_remote_game.py
`--dump` is now called `--write-replay`
`--store-output` will write the player’s stdout and stderr into the specified folder. Note that this needs to be done unbuffered or else we will lose the most important messages (the reason why a bot crashed).
=> Renamed --dump and added storage option for a player’s stdout/stderr

pelita/scripts/pelita_player.py
A team with `TEAM_NAME="error"` would be detected as returning an error dict (Team returns `{'error': (error_type, error_msg)}` when it has detected an exception in the client), as it would return the team name string after `set_initial`.
In a future revision, we should have `set_initial` return a dict as well (and probably change the return dict in case of error to `{'error': error_type, 'error_msg': error_msg}, too).
Needs a test of some sort. This is an error of the kind that will pop up again eventually.
=> BF: Allow team names that include the string ‘error’.

pelita/layout.py, pelita/player/team.py, pelita/utils/__init__.py, test/test_layout.py, test/test_team.py
Adds a new functionality to `parse_layout` that accepts the layouts that are accepted in `setup_test_game`
layout = """
########
#01..EE#
########
"""
parse_layout(layout, allow_enemy_chars=True)['enemy'] == [(5, 1), (6, 1)]
Additionally, it fixes #617 
Still work in progress while I rewrite `pelita.utils.create_layout` to use this function instead of it’s own class-based representation.
The main problem I have with the API is that now we have two types of layout. First, the 4 bot based one that we use in all our provided layouts, and then the team-centric one with 2 bots, 2 enemies. They are both dicts and their only difference is that the latter one has a key `"enemy"` and the list of bots has only a length of 2. I fear this will be very confusing at some point or even lead to weird …
=> Add enemy character handling to parse_layout

pelita/ui/tk_canvas.py, pelita/ui/tk_viewer.py
Previously the grid view would not include the bottom and right border lines. We had to adjust the Mesh class to take this into account.
Co-authored-by: @otizonaizit
=> Adjust mesh calculations to include right and bottom lines of grid in canvas.

setup.cfg
pytest is needed for the tests also in pelita_template, so it makes
sense if it gets installed unconditionally together with pelita.
networkx is not strictly a dependency, but it makes sense to use it
in pelita_template, and it is indeed used already in some demos, so
let's have it also for pelita, given that pelita_template will come
back to the main repo at some point.
=> Promote pytest and networkx to dependencies for pelita

pelita/game.py, pelita/player/team.py
Closes #485.
The speed increase is not super big (10–20% faster), so I am not 100% sure, if we really do need it. However, compared to pelita from September 2018, we are almost three times slower, when running a game with stopping players on a big layout… At some point we should see, if profiling helps (or cache the height/width of the layout, which I am almost sure is a factor).
=> ENH: Only transmit the walls during set_initial phase

pelita/utils.py
Adds a new helper function to `pelita.utils` that can be used to load a builtin layout in a way that it can be passed to `setup_test_game`:
layout = load_builtin_layout("small_without_dead_ends_001", is_blue=True)
setup_test_game(layout=layout, is_blue=True)
If this is the proper way to do it is still up for discussion.
=> NF: Add utils function to load a builtin layout for a team

pelita/layout.py, setup.cfg
New in Python 3.7 (but backported for earlier versions). Comes with a nicer API, too.
=> Use importlib.resources instead of pkg_resources

.travis.yml, pelita/tournament/tournament.py, test/test_remote_game.py
I think I have found our problem with the flushing. (Running `call_pelita` does not always return the last line in the game. Ie. ‘Finished’ is never printed.)
The problem is probably not flushing (we do in fact flush in `ResultPrinter` which prints the final line). The problem is that before we print the last line, we already tell `call_pelita` via zmq that the game is over. Therefore, `call_pelita` decides that it can as well exit and tries terminating out main pelita process. In most cases all is well and the main pelita process has already printed and exited. Sometimes it will be forcefully terminated before it can print.
This fix adds a small `wait(1)` after the `call_pelita` loop has received the message that the game has ended, which should be enough time for pelita to finish all …
=> ENH: Increase the chance that call_pelita flushes correctly to stdout.

pelita/ui/tk_sprites.py
This PR increases the thickness of all walls in the TK UI. This way it is easier to see how many squares are there between wall tunnels, for example. 
Also, fill in squares of walls. Until now there is empty space within a square of walls, and it seems it would be reachable. If we go for this thickness, then maybe the color of the walls could be made a little lighter.
Two screenshots on two different layouts to appreciate the change.
Master branch (example 1):
This PR (example 1):
Master branch (example 2):
This PR (example 2):
=> Better walls for TK UI

test/test_remote_game.py
This makes the remote game tests running each time on different ports. Let see if this helps fixing the random TCP freezes that we get when running pytest either on the CLI or on travis
=> Use random ports when running remote game tests to avoid random TCP freezes during tests

pelita/game.py, pelita/player/FoodEatingPlayer.py, pelita/player/RandomExplorerPlayer.py, pelita/player/RandomPlayers.py, pelita/player/SmartEatingPlayer.py, pelita/player/SmartRandomPlayer.py, pelita/player/StoppingPlayer.py, pelita/player/base.py, pelita/player/team.py, pelita/utils.py, test/demo01_stopping.py, test/demo02_random.py, test/test_game.py, test/test_network.py, test/test_remote_game.py, test/test_team.py
Things are simpler if we always initialize the state to be an empty
dictionary, and simply pass the same mutable object always to the move
function. In cases where the player does not actually use the state to
store anything, it can ignore the variable completely. The object also
has always the same type (dict), so there is less chance of trying to
a TypeError.
=> Do not return state from move()

pelita/ui/tk_canvas.py
On some systems (and consistently on the new macOS) tk would try to draw the game’s background before the `screen_width` (coming from `canvas.winfo_width()`) was properly initialised. The default value for the width could therefore be 1. Together with our August sprint addition that introduced padding for the canvas (#640) with the following formula
def rect_width(self):
""" The width of a single field.
"""
return float(self.screen_width - 1 - 2 * self.padding) / self.mesh_width
this meant that in some circumstances the `rect_width` would become negative, which in turn would be used to calculate the line width of the maze. Drawing a line with a negative width would then crash Tk with the error given in #693:
_tkinter.TclError: bad screen distance "-0.0625"
This fix just returns 0 for the …
=> BF: rect_width/rect_height should never return negative values.

pelita/layout.py, pelita/scripts/pelita_main.py, pelita/utils.py, test/test_layout.py
We also had our own private instance of the glob.glob('*') (non-)sorting mistake, where we assumed that that listing a directory returns the filenames sorted, when it actually does not. The global instance of this mistake made the headlines:
https://arstechnica.com/information-technology/2019/10/chemists-discover-cross-platform-python-scripts-not-so-cross-platform/
=> Fix a long standing bug where we assume sorted filenames

pelita/game.py, pelita/scripts/pelita_main.py, test/test_game.py
Previously, this was only a global variable `MAX_ALLOWED_ERRORS ` in `game.py`, even though we did have an empty, non-used API slot (with a default) in `def run_game` and `def setup_game` and an argument in the command line interface `--max-timeouts` that was not functional either.
I have rewired everything to make use of the flag and renamed the CLI to `--max-errors`, which is hopefully more clear. Note that I also changed the defaults to 4, as in my opinion the name `--max-errors` implies the maximum number of errors that are still allowed and our rule is ‘(minimum) five timeouts and you’re out’ (open for suggestions to change the wording and default to be 5 again, but `--num-errors-to-die` does not sound much nicer).
For running games without error checking (might be useful for …
=> Put max_team_errors in game state

pelita/game.py, pelita/scripts/pelita_main.py, test/test_game.py
Setting the error_limit to zero will disable error counting. As discussed in #709 we can still settle on a different name.
=> RF: Change max_team_errors to error_limit (and shift logic by one).

pelita/layout.py, setup.cfg
This means that we *might* make `gamestate` a `@dataclass` in the future.
=> BLD: Drop official support for Python 3.6

check_layout_consistency.py, demo/benchmark_game.py, pelita/game.py, pelita/gamestate_filters.py, pelita/layout.py, pelita/network.py, pelita/player/team.py, pelita/ui/tk_canvas.py, pelita/utils.py, pelita/viewer.py, test/test_filter_gamestates.py, test/test_game.py, test/test_layout.py, test/test_network.py, test/test_team.py
Work in progress (discussion) PR. **Do not merge yet!** Closes #673.
This PR tries to optimise two critical bottlenecks in the Pelita backend:
* It is costly and error prone to get the shape of the maze, which now uses the pattern `width = max(walls)[0] + 1`, `height = max(walls)[1] + 1`. And this has to be repeated every time we use it. The `+1` is easily forgotten. As we are sorting the walls, it might be enough to assume `max(walls) == walls[-1]` to speed this up.
* It is costly to check whether a position is in a wall (or in the food list) (eg. the pattern `if position in gamestate["walls"]`), and even costlier to check when it’s not, as the whole list needs to be traversed every time.
Both problems can be solved by adding a tuple `shape` to the layout and by using a `(frozen)set` …
=> Adding shape to layout dictionary and optimising access

pelita/game.py, pelita/ui/tk_canvas.py, pelita/ui/tk_sprites.py, test/test_game.py
(Work in progress. Will be rebased and become more refined eventually.)
This adds a bot’s line of sight in debug mode. Any enemy bot within the line of sight will appear at its exact position (and therefore will not have a ghost bot appear).
Note that the line of sight is drawn from a bot’s position *before* a move, while the UI will show it’s position *after* a move. To make this more clear, we show a border around the initial cell (or maybe we should colour the cell; will still experiment with this) and put an arrow in the direction of the move that was requested.
When a move was invalid and a random move is executed instead, we show an X on the original cell (design need to be refined).
How should we show that a move was a stopping move? Perhaps with this circular arrow? (This version …
=> Add line of sight and intention arrows

pelita/game.py, pelita/player/team.py
This ends the game when it is stared like as follows
pelita my_player/ remote:tcp://remote.server:8087
but when there is no remote player running on remote.server:8087 (which would have to be started as `pelita-player --remote tcp://remote.server:8087` but isn’t). We now catch the PlayerTimeout and count a win for the team that has successfully connected. Previously, Pelita would raise the `PlayerTimeout` exception and exit.
This might fix a similar situation that was discussed #269, which I am also closing now.
I had to introduce an additional `socket.setsockopt(zmq.LINGER, 0)`, otherwise Pelita would never exit as the zmq Context was never destroyed. In a follow-up issue I’ll detail what needs to be done some point in the future to fix this once and for all.
=> BF: Let a remote player lose when it cannot connect in time.

pelita/player/FoodEatingPlayer.py, pelita/player/SmartEatingPlayer.py, pelita/player/SmartRandomPlayer.py, test/test_players.py
That one’s for the best-of-fails collection in the Pelita bug hall of fame.
What’s the problem with the following assignments and how does this make you feel about Python being an untyped language?
```python
def smart_random_player(bot, state):
dangerous_enemy_pos = [enemy.position
for enemy in bot.enemy if enemy in enemy.homezone]
killable_enemy_pos = [enemy.position
for enemy in bot.enemy if enemy not in enemy.homezone]
```
Of course, `enemy.homezone` is a `Set[(int, int)]`, so the check `enemy in enemy.homezone` is always `False`, rendering all enemies instantly non-dangerous and killable. Perhaps `enemy.homezone` should raise a `ValueError` when the types are incompatible.
(Tests copied over from the pelita_template code.)
=> Fix error in SmartRandomPlayers that would make enemies invincible.

pelita/scripts/pelita_tournament.py, pelita/tournament/__init__.py
Half-closes #737. Doesn’t yet include the group id in the GUI.
The group ID assumes a specific format of the tournament config (groups
are indexed in the order given there; a future improvement would make
the group ids explicit in the tournament config).
=> ENH: Show group numbers before a match.

pelita/tournament/__init__.py, pelita/tournament/roundrobin.py, test/test_tournament.py
This commit optimises the matchplan in the round-robin tournament, making it fairer and (hopefully) more fun:
a) At any point each team should have a similar number of played games
b) No team should play two games directly after another;
both of these points should make the tournament more interesting to follow.
Finally, in the interest of fairness:
c) Blue and red teams (ie. who starts the match) should be assigned evenly.
As having five teams is the usual case during ASPP student tournaments, we special-case this one and implement the circle method in all other cases.
There are 10 games to be played in a single round-robin tournament with 5 teams, which means that there are 10! = 3628800 possible arrangements (ignoring blue/red difference). Some of then are obviously pathologically bad, …
=> RF: Improve matchplan in round robin-tournament

pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, setup.cfg, test/test_game.py
This commit adds basic support for zeroconf-based networking.
Instead of a player location, pelita now understands the keyword `SCAN`
to search for remote players that advertise themselves via zeroconf:
pelita ./own_player SCAN
A zeroconf-based remote player can be started with the argument
`--advertise` like so:
pelita-player --advertise --remote ./some_bot.py tcp://192.168.1.23:10027
Demo:
https://user-images.githubusercontent.com/216179/168391205-0d130500-2295-47e0-92bb-9b4883e43d95.mov
Commit needs https://github.com/jstasiak/python-zeroconf and https://github.com/Textualize/rich (eye-candy) to run.
Not sure if we can call our service `_pelita-player._tcp`. For IANA correctness, we might want to create a uuid.
=> WIP: Adding support for zeroconf

CHANGELOG.md
- Do not have a team play two matches in a row during round-robin mode
- Show the tournament group names in the UI and on the CLI
- Automatic detection of network players via zeroconf
=> BLD: v.2.2.0-rc1

CHANGELOG.md, pelita/__init__.py
Release Pelita v2.2.0, the Bilbao edition. Closes #744
=> BLD: v2.2.0

pelita/ui/tk_canvas.py
On (at least) Debian, tkinter is not installed by default, so let's fail with an informative message for the user. If the Linux OS is not Debian-based, the package to install has a different name. I am not sure if non-Debian distributions do not install tkinter by default either.
=> On (at least) Debian, tkinter is not installed by default

pelita/scripts/pelita_main.py, pelita/viewer.py
Closes #779 
Also using the rich progress viewer now.
We need to be careful not to pass everything to rich, as it makes the ASCII game slower. Also, the rich auto detection will colourise `...` which occurs in some game layouts.
Tested on Windows. ✓
=> Use rich for terminal viewers to fix colouring issues on Windows

pelita/team.py
The bot attribute `bot.legal_positions` used to be a property, i.e. the list of positions got generated on the fly every time the code tried to access `bot.legal_positions`. This could be surprising, especially if the code was trying to implement something like "remove the enemy positions from the legal positions so that I run accidentally on top of an enemy".
We have seen repeatedly code like this:
```python
1 if bot.enemy[0].position in bot.legal_positions:
2     bot.legal_positions.pop(bot.enemy[0].position)
3 if bot.enemy[1].position in bot.legal_positions:
4     bot.legal_positions.pop(bot.enemy[1].position)
5 
6 for new_pos in bot.legal_positions:
...
```
The problem with this code if `bot.legal_position` is a dynamically generated list is that it would run without generating any …
=> Make legal_positions a static attribute instead of a dynamic property

.github/workflows/test_pytest.yml
codecov-action@v4 fails with upload errors although I provided a token. Maybe we don’t need both codecov + coveralls anyway, so I am giving up on this one for now.
```
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit'
/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit --git-service github -Z
==> Uploader SHASUM verified (e70beb7c9e3d894678e7d4d0fcb94e59133212dbda5ca7406b625a0167ce4ca8  codecov)
info - 2024-04-21 10:52:22,182 -- ci service found: github-actions
warning - 2024-04-21 10:52:22,190 -- No config file could be found. Ignoring config.
info - 2024-04-21 10:52:22,401 -- Process Commit creating complete
error - 2024-04-21 10:52:22,401 -- Commit creating failed: {"detail":"You do not have permission to …
```
=> CI: Removing codecov

pelita/team.py, pelita/utils.py, test/test_team.py
Introduce a new cached attribute `graph` to the `Bot` object.
This PR also moves the `walls_to_graph` function from `utils.py` to `team.py`, where it arguably now belongs. An alias `walls_to_graph` is left in `utils.py` for backward compatibility.
Fixes: #789
=> add a new `graph` cached attribute to the `Bot` object

test/test_team.py
Check that weights are not immutable in a graph view and ensure that both bots see a view to a different cached graph.
=> Check that weights can be changed in the graph.

pelita/game.py, pelita/network.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, pelita/scripts/pelita_server.py, pelita/team.py, pelita/viewer.py, pyproject.toml, test/test_network.py, test/test_remote_game.py
Will still need refinements (that I’m still working on) but already runs and closes #776 and #769.
The short news is you start a Pelita server like this:
pelita-server remote-server  --address 0.0.0.0 \
--team ../BayesAvengers.py avengers \
--team ../trilobots.py trilobots \
--advertise 10.10.1.2
(--advertise is only needed when we want to use zeroconf)
This will start a server on port 41736 (which is the default for the new URL scheme) and we can run a match with both teams on the server as follows:
pelita --ascii pelita://10.10.1.2/avengers pelita://10.10.1.2/trilobots
(The specific IP should not be needed and could also be a hostname.)
When the network allows for using zeroconf then it should also be possible to use SCAN and detect all players on the server automatically.
It is not …
=> Improved Pelita server mode

pelita/scripts/pelita_server.py
Closes #799 by putting outgoing messages in a send queue.
Shielding individual sends with a timeout is not sensible here as it would stall the server when there are crashed bots.
Draft because I am not sure if this is a good design.
=> RF: Add a send queue for outgoing messages to avoid broken players stalling the server

pelita/ui/tk_canvas.py
Fix longstanding bug introduced in 92ca5553f61e05c5edaf9f3bd240628bb1ef06f8
The homezone for the blue team shown in the field status (bottom right) is one square too big. Typical off-by-one error ;-)
(see screenshot)
=> BF: TK UI shows wrong homezone for blue team

pelita/game.py
As was mentioned in https://github.com/ASPP/pelita/pull/804 we sometimes have timeouts in our CI. In this case, it could be tracked down to the test:
pytest test/test_remote_game.py::test_remote_move_failures[player_move_import_error-False-ModuleNotFoundError]
I cannot reproduce it right now but it is likely that one of two things happens:
The tested player has an import error, so the game setup fails and triggers a fatalerror. This error causes the game to finish and we end up in `def check_exit_remote_teams` where we notify the players of how the game went down and that they should shut down. As the player has already had a fatal error this can
a) cause a hang in zmq.send (similar to https://github.com/ASPP/pelita/issues/799); this should actually have been taken care of with our helper …
=> Do not attempt to send an exit message to a team with a fatal error

contrib/ci_engine.py, contrib/test_ci_engine.py
Adds the team name that is detected on startup to a separate database and uses the cached value later.
Closes #814
=> Add team name to CI engine if available

pelita/game.py, test/test_filter_gamestates.py, test/test_team.py
In Heraklion we noticed that the value 3 for the shadow distance for food relocation was a bit too broad. It made a purely attacking strategy overwhelmingly more worth investing than a defending or mixed strategy. by reducing the shadow to 1 we still avoid pure camping, but still make it worth to explore defending strategies.
I know it all sounds quite hand-wavy, but it is very difficult to put numbers onto this reasoning.
=> Reduce default shadow distance to 1

pelita/maze_generator.py, pelita/scripts/pelita_createlayout.py
This PR does not change the default generation algorithm, so mazes are still generated without dead-ends and chambers by default.
=> Make it possible to generate mazes with dead ends and chambers

pelita/game.py, pelita/layout.py, pelita/scripts/pelita_main.py, pelita/utils.py, test/test_layout.py
Use the newly defined layouts with dead ends. This PR also sets a default proportion of 0.25 for the layouts with dead ends, which means that every 4th game will have a layout with dead ends.
This PR should be merged after #823 and #824
=> Use dead ends

pelita/game.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_tkviewer.py, pelita/ui/tk_canvas.py, pelita/ui/tk_viewer.py
=> NF: Add --stop-after-kill option

pyproject.toml
Not sure whether this signifies ‘project age’ or ‘release age’, ie. should this be changed in case we have a beta before a bigger release. In any case, I’d say Pelita has grown up by now. 🥳
=> 🔞 ░m░y░ ░b░o░t░s░ ░i░n░ ░p░r░o░f░i░l░e░

pelita/maze_generator.py, pelita/scripts/pelita_createlayout.py, test/test_maze_generation.py
Plus bonus commit: rename `get_new_maze` → `create_maze` which to me follows more common API conventions. If this is merged, I suggest that #856 is rebased.
@otizonaizit Do you know why you close the stdout stream? I assume flushing is enough?
=> Fix maze_generator still using old seed argument to get_new_maze

pelita/ui/tk_canvas.py
Labels are not auto-scaled (the margin is also not auto-scaled so it should always fit, unless of course, we have more than 100 cells in one dimension or so).
=> ENH: Add axis labels to grid mode.

pelita/game.py, pelita/network.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_tkviewer.py, pelita/ui/tk_canvas.py, pelita/ui/tk_sprites.py, pelita/ui/tk_viewer.py
I hope to have a beta ready until tomorrow. The basic idea is that in one window, one starts a Tk viewer as:
pelita-tkviewer --standalone-mode tcp://127.0.0.1:8888
which binds to port 8888 and will display any layout that is sent to it. This means that one should keep this window opened but can quickly send layout snapshots from for example an open ipython session.
In addition, I added a small overlay protocol that can (currently) colourise the background of the individual cells. Nothing fancy but we can now have a different colour for each chamber, for example.
The feature is currently Pelita-developer oriented. Not for users.
Closes #854 .
=> WIP: Standalone viewer with overlay graphics

pelita/team.py, test/test_team.py
Now, when Pytest is run with the `-l` flag and a bot object is in scope, it will be shown as
bot        = <Bot: a (blue), (5, 2), turn: 0, round: None>
Closes #847
=> Add Bot.__repr__ (useful in Pytest error contexts)

pelita/ui/tk_sprites.py
use the mesh_width dynamically for deciding if a bot must be drawn as ghost or pacmen. At init time the BotSprite could be initialized on an still empty maze.
Fixes: #865
As an alternative to #866
=> Choose to draw a ghost or a pacmen dynamically depending on mesh size

pelita/layout.py, pelita/maze_generator.py, test/test_maze_generation.py
Hey guys,
analogous to #852, I also tried to use the first version of the optimized chamber finding algorithm in the maze generation as well.
The timings went from several seconds down to less than half a second consistently for script execution.
However, looking at the profiling, only 5% (25 ms) are actually maze generation and the rest of the time was spent in importing:
<details>
<summary>absolute times</summary>
```
_     ._   __/__   _ _  _  _ _/_   Recorded: 09:47:34  Samples:  233
/_//_/// /_\ / //_// / //_'/ //     Duration: 0.480     CPU time: 1.285
/   _/                      v5.0.1
Program: scripts/pelita_createlayout.py
0.479 <module>  pelita_createlayout.py:1
├─ 0.299 <module>  ../__init__.py:1
│  └─ 0.297 <module>  ../game.py:1
│     ├─ 0.183 <module>  ../team.py:1
│     │ …
```
=> Optimize Maze Generation

pelita/game.py, test/test_game.py, test/test_player_base.py
This is the minimal implementation of making illegal moves a fatal error.
Given that the only other possible non-fatal error are timeouts, it may be worth it to refactor the error handling. I decided not to try this in this PR, because it would be a lot of work and I'd like this minimal implementation to go into the next release, so that we can start seeing the benefits right away. After all the error handling is not a user-facing feature.
In the process I fixed some tests that were still using the old API for the move function and were working because of the side effect of having `error_limit=5`, but these bots were returning invalid positions all along...
If and when this PR is merged I'll have a go at updating the docs in pelita_template.
Fixes: #832
=> Make returning an illegal position a fatal error

pelita/team.py
The `Bot.is_noisy` attribute has historically being perceived as confusing. The attribute `Bot.has_exact_position`, internally implemented simply as `not bot.is_noisy` conveys the intent in a clearer way.
More discussion about this in this issue in the pelita_template repo:
https://github.com/ASPP/pelita_template/issues/85
=> add `Bot.has_exact_position` attribute

pelita/team.py, test/test_team.py
=> Sanitise all whitespace characters in bot.say

pelita/ui/tk_canvas.py, pelita/ui/tk_viewer.py
As the title says.
You can now go backward and forward in time.
Also, the button styles were changed.
Fixes: #82
=> Add History to Tk Viewer

pelita/ui/tk_canvas.py
I think this makes the code a little nicer :) (Plus it fixes a bug: SHIFT+ENTER would flicker the status)
Arguable change: When we return to the current step we exit ‘playback mode’ again. (I like this behaviour more but most of all it was way easier to implement.)
=> RF: Simplify the history status
