ASPP/pelita

pelita/game_master.py, pelita/player.py, pelita/simplesetup.py
Yeah, I know. It looks rather ugly. We should drop Python 2. :)
=> BF/ENH: Use monotonic time for time differences when possible

pelita/containers.py, pelita/datamodel.py, test/test_datamodel.py
=> BF: neighbourhood should not return positions outside of the maze.

layouts/create_maze.py, layouts/create_pelita_layouts.py, layouts/maze_generator.py, pelita/layout.py
@otizonaizit @pberkes I have removed the `mdp.graph` import because I could not install it with pip. :disappointed:
I don’t mind keeping it in as a historic reference, though. :)
=> ENH: Creating mazes with Python 3.

.travis.yml, demo/demo_simplelocalgame.py, doc/source/groupN/__init__.py, doc/source/groupN/my_player.py, doc/source/groupN/utils.py, doc/source/my_player/my_player.py, module_player.py, pelita/libpelita.py, pelitagame, tkviewer.py
=> ENH: Change all #! to python3.

doc/source/writing_player.rst, pelita/player.py
=> NF: Adding enemy_name to AbstractPlayer.

.travis.yml, test/test_datamodel.py, test/test_graph.py, test/test_player.py
Closes https://github.com/ASPP/pelita/issues/329
=> BLD/BF: Adding Pypy and Python 3.5 support.

pelita/ui/tk_canvas.py
<, >         : Decrease speed, increase speed
spacebar     : Start/stop toggle
enter        : Play step
shift+enter  : Play round
numbersign # : Toggle grid
=> ENH: Adding a few helpful shortcuts to the Tk interface

pelita/ui/tk_viewer.py
Closes https://github.com/ASPP/pelita/issues/345
=> ENH: Force pelita on top.

players/SmartEatingPlayer.py, players/__init__.py, tournament/test/test_tournament.py
This player is similar to the FoodEatingPlayer with the difference
that it will not run into another Bot but instead will stop and choose
a new food to eat in the next round.
It should always win against a StoppingPlayer, except for the most pathological
of layouts.
=> ENH: Introducing SmartEatingPlayer.

pelita/player.py
Not strictly needed (we won’t teach how to use it) but allows us to be a bit more concrete about the API that we’re expecting.
=> NF: Adding AbstractTeam for better API docs.

pelita/libpelita.py, test/test_libpelita.py, tournament/tournament.py
=> BF: Fix argparse/config for speaking.

pelita/graph.py, test/test_graph.py
This PR combines the merging of #371 and #372 with one additional test derived from @Debilski's https://github.com/ASPP/pelita/pull/371#issuecomment-246354164 . 
Ready to merge in my opinion.
Closes #371,  closes #372.
=> FIX/TST: Merge #371 and #372 and add additional test

tournament/tournament/tournament.py
This shuffles the order of teams in a deathmatch. Unfortunately,
this is not stored in the state because shuffling is only done inside the
start_match function.
Closes #353
=> NF: Shuffle teams in a deathmatch.

test/test_containers.py, test/test_datamodel.py, test/test_game_master.py, test/test_graph.py, test/test_layout.py, test/test_libpelita.py, test/test_pelitagame.py, test/test_player.py, test/test_simplesetup.py, tournament/test/test_tournament.py
=> Drop unittest verbosity, go full py.test

pelita/ui/tk_canvas.py
Closes #385 (though it can still need more UI niceties).
=> ENH: Show why a team has been disqualified.

test/test_player.py
=> BF: Fix random test failure due to pytest conversion.

tournament/test/test_tournament.py, tournament/tournament/tournament.py
=> BF: Disallow numeric ids.

pelita/player.py, test/test_player.py
=> ENH: Add simulate_move to AbstractPlayer.

tournament/tournament/tournament.py
Small bug fix. Should be done more thoroughly in libpelita, though.
=> BF: Allow tournament to find pelitagame from any directory.

pelita/simplesetup.py
We somehow forgot to change it in SimpleServer
=> ENH: Set the rounds default to 3000 everywhere.

pelita/player/__init__.py, pelita/player/base.py, test/test_game_master.py, test/test_player_base.py, test/test_simplesetup.py
=> RF: TestPlayer → SteppingPlayer

pelita/scripts/pelita_tournament.py
=> NF: Warn that the log files be copied after the tournament.

pelita/__init__.py
=> BLD: 0.9.0rc0

pelita/graph.py
=> BF: Fix a_star error message.

pelita/datamodel.py, test/test_datamodel.py
fixes issue #49 
see pull request #429
=> NF/UT: added on_west_side property for bots and a test for it

doc/source/writing_player.rst, pelita/game_master.py, pelita/graph.py, pelita/player/FoodEatingPlayer.py, pelita/player/SmartEatingPlayer.py, test/test_graph.py
We can also decide whether we want to get rid of the `dict` inheritance there.
=> Rename AdjacencyList to Graph

pelita/datamodel.py, test/test_datamodel.py
This might debug-printing a little easier to understand.
=> ENH: repr of Team and Bot now contains the keywords to all arguments.

README.tournament.md, doc/source/groupN/__init__.py, doc/source/my_player/my_player.py, doc/source/running_player.rst, doc/source/writing_player.rst, pelita/player/FoodEatingPlayer.py, pelita/player/RandomExplorerPlayer.py, pelita/player/RandomPlayers.py, pelita/player/SmartEatingPlayer.py, pelita/player/SmartRandomPlayer.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py
Players are now required to export a method
def team():
return SimpleTeam(…)
from their modules.
NB: This is a breaking change!
=> UX improvement: The default factory is now called ‘team’

pelita/libpelita.py
=> BF: Fix format strings in error handling.

pelita/ui/tk_canvas.py, pelita/ui/tk_viewer.py
Before, the first frames would show a too huge canvas. Now we improved
the size estimate and call canvas.update after building the UI.
=> BF: Improve calculation of canvas size.

contrib/ci.cfg, contrib/ci_engine.py
Updated ci_engine to use libpelita instead of command line parsing.
=> BF: Use libpelita in the ci_engine.

pelita/ui/tk_viewer.py
Tk will fail when no $DISPLAY env variable is set. If this happens and
the Tk code is responsible for calling the controller, we send an exit
messsage to the controller (and thereafter exit ourselves). This means
the game will immediately shut down.
Solves #407 in the viewer. Fixes #102.
=> ENH: Tell the controller when Tk init fails.

.travis.yml, setup.py
Python 3.7 and some minor cleanup of the travis.yml
=> BLD: Python 3.7

pelita/game_master.py, pelita/scripts/pelita_tkviewer.py, pelita/simplesetup.py, pelita/ui/tk_canvas.py, pelita/ui/tk_sprites.py, pelita/ui/tk_viewer.py, pelita/viewer.py, test/test_game_master.py
=> ENH: Clicking on a field shows the coordinates and other Tk UI enhancements

pelita/ui/tk_sprites.py
=> BF: UI fix for kamikaze bots.

pelita/scripts/pelita_player.py, pelita/simplesetup.py
pelita_player will now intercept when load_team fails and return an
error message object to the zmq socket. The ZMQConnection has been
adapted to close itself and raise a connection error on retrieval.
As a quick fix, the error message is returned from set_initial as the
team name so that it can be shown in the UI.
Further updates should make this a bit more flexible and refined.
Positive changes: A typo on the command line or a syntax error in a player will not freeze the UI for 3 seconds anymore.
Needs some more testing before merging. Also I might still rename some of the exceptions.
=> ENH: First draft for error-handling capabilities in the zmq protocol

pelita/ui/tk_canvas.py, pelita/ui/tk_sprites.py
=> ENH/Tk: Show the bot id when the grid is enabled.

doc/source/index.rst, doc/source/rules.rst, doc/source/writing_player.rst
Fixes https://github.com/ASPP/pelita/issues/476 
Related: did you guys ever tried to change the winning condition to eating all the enemy's food first regardless of how many times you die? I guess this would change the strategies quite a bit, but for good or for bad?
=> DOC/ENH: add a "rules" section to the docs

doc/source/rules.rst, pelita/game_master.py, pelita/scripts/pelita_main.py
Previously, it was only reported as a timeout. Now we also specify the reason when it came from an illegal move.
=> ENH: Report illegal moves on the command line.

pelita/libpelita.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_tkviewer.py, pelita/ui/tk_canvas.py, pelita/ui/tk_viewer.py
Currently the first step of the round will be executed. This should be fixed in a future revision.
=> ENH: Added --stop-after flag which stops the game in the given round.

pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py
Either specify both or you get a demo game.
=> get rid of automatic selection of random opponents.

pelita/libpelita.py, pelita/scripts/pelita_player.py
Either specify both or you get a demo game.
=> print team color on console output

pelita/player/team.py
... so that we can use them in tests
=> initialize _track and _eaten internal variables in Bot object

pelita/player/team.py
=> add stop, i.e. (0,0), to the list of legal_moves

pelita/player/team.py, test/test_team.py
=> Remove other and team from Bot

pelita/simplesetup.py
=> BF: Returning numpy.int64 does not kill the player anymore.

pelita/scripts/pelita_main.py
Closes #453. (To be rebased after #535 has been merged.)
The ReplayPublisher now includes controller functionality, which means that the Tk viewer can now request the next frame, when it wants to.
This means that we can get rid of the more or less arbitrary sleep functions for proper synchronisation. Additionally, we can now pause the replay and step through it. (Stepping through rounds is not implemented yet.)
Some further restructuring of the init logic in `pelita_main` has also been done.
=> Controllable replay mode

pelita/player/team.py
=> ENH: Make Bot.track writable.

pelita/game.py, test/test_game.py
They are very nice. Also not really done. Sorry.
=> V2.0 Added tests for game module

pelita/__init__.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_tkviewer.py
=> RF: Only evaluate git version on demand.

pelita/game.py, pelita/player/team.py, pelita/scripts/pelita_player.py, pelita/simplesetup.py, test/test_game.py
Needs still some polishing and more tests (one assertion fails because game does not return a draw when both teams fail fatally).
=> Improved error propagation when a client errors

pelita/player/FoodEatingPlayer.py, pelita/player/RandomExplorerPlayer.py, pelita/player/RandomPlayers.py, pelita/player/SmartEatingPlayer.py, pelita/player/SmartRandomPlayer.py, pelita/player/StoppingPlayer.py, pelita/player/__init__.py, pelita/player/base.py, test/test_game_master.py, test/test_pelita_player.py, test/test_player_base.py, test/test_players.py
Also the tournament tests should work again now.
=> Rewritten internal players and tests

pelita/game.py, test/test_game.py
gamestate["team_time"] is now measured again.
=> Reenabled the team time

pelita/scripts/pelita_player.py
Remove someone unneeded stuff.
=> Clean up pelita player

contrib/ci_engine.py, pelita/network.py, pelita/player/team.py, pelita/scripts/pelita_player.py, pelita/simplesetup.py, test/test_game.py, test/test_libpelita.py, test/test_network.py
Removes the single-purpose class SimpleClient and does the request–reply handling more explicitly in pelita_player now.
=> Add SimpleClient code to pelita_player

pelita/player/team.py, test/test_player_base.py
=> RF: Bot.legal_moves → Bot.legal_directions

pelita/game.py
Conda regularly defaults to Python 3.6, depending on the package that one installs, so I think it is still useful to be Python 3.6 compatible.
That said, I still prefer writing out the game state attributes in a class-like structure, as it makes documenting the attributes and their types much more obvious. However, doing this manually without the help of `@dataclass` results in unneeded (and brittle) code duplication, so we should probably keep it like this.
Not sure, if it is useful to make this a separate function `make_gamestate` since it will also result in much duplication. This means, that `setup_game` will be the *only* canonical way to create a game state.
=> RF: Remove dataclass for Python 3.6 compability.

pelita/ui/tk_canvas.py
=> ENH: Add traffic lights to Tk to show current bot.

pelita/game.py, pelita/player/team.py, test/test_game.py
=> ENH: Exit remote teams when the game is over.

pelita/ui/tk_canvas.py
- makes subtitle status line font smaller and more spaced from title (now the two lines should not overlap anymore (needs to be tested on anaconda and Mac)
- still some other cleanups here
=> WIP: TK-ui cleanups

pelita/layout.py, pelita/player/team.py, pelita/utils.py, test/test_layout.py, test/test_utils.py
> print(bot)
StoppingBots (you) vs Random Explorer Players.
Playing on blue side. Current turn: 1. Round: 2, score: 0:0. timeouts: 0:0
################################
#. .#  # #  #     ##.#######   #
#. .# ##.#  #       .   .      #
#0###### ##.##   . .  #... ##  #
#1             ##     .   ..   #
################################
Not sure if this is legible enough?
Closes #622
=> Show noisy enemies with a questionmark

pelita/tournament/tournament.py, test/test_libpelita.py, test/test_remote_game.py
Seeds must be int or a string that can be converted to an int.
=> Ensure that seeds in call_pelita are valid

pelita/scripts/pelita_main.py
Minor adjustements to the pelita CLI:
- unify the `--layout` and `--layoutfile` options
- update the example team specification to match the new API
=> Refactor pelita CLI

README.md
=> DOC: Updated README.md

pelita/game.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_player.py, pelita/scripts/pelita_tkviewer.py, pelita/scripts/pelita_tournament.py, pelita/scripts/script_utils.py, pelita/utils.py, test/test_utils.py
Document user-facing functions
Fixes: #671
=> document user-facing functions in utils

README.tournament.md, check_layout_consistency.py, contrib/ci_engine.py, pelita/game.py, pelita/layout.py, pelita/maze_generator.py, pelita/scripts/pelita_tournament.py, pelita/tournament/__init__.py, pelita/ui/tk_viewer.py, pelita/utils.py, test/test_filter_gamestates.py, test/test_remote_game.py, test/test_team.py
git ls-tree -rz --name-only HEAD | xargs -0 codespell -w
=> Typo fixes with codespell

pelita/game.py, pelita/utils.py
Closes #679
Need test (possible rename) and will need to be added to the scripts in utils.
=> ENH: Add flag to silence run_game

pelita/layout.py, test/test_layout.py
=> Fix, improved doc and test for layout_agnostic()

pelita/__init__.py
Not sure if it’s really needed but it could avoid some confusion. A proper release should include a few more fixes than just the API change.
=> BLD: Bump version to 2.1-pre to signalise recent API changes

pelita/game.py, pelita/ui/tk_canvas.py, pelita/ui/tk_sprites.py
We’ll need to spend some more time to make it look less intrusive.
Closes #347
=> NF: Add shadow bots to Tk UI

pelita/player/team.py, test/test_team.py
+ tests for `str(bot)` and `bot._repr_html_()`
=> Fix IPython repr of Bot

pelita/game.py, pelita/player/team.py
Closes #716 .
Subject to change in case we find a better solution or variable.
=> Add option to hide output of bots in subprocesses.

contrib/ci_engine.py, pelita/scripts/pelita_main.py, pelita/tournament/__init__.py, test/test_libpelita.py, test/test_remote_game.py
[Python docs](https://docs.python.org/3.8/library/subprocess.html#using-the-subprocess-module) say `subprocess.run` is recommended nowadays.
=> RF: Use subprocess.run instead of check_* API.

.github/workflows/push_ci.yml, .github/workflows/pypi_release.yml, README.md
ASPP 2021 will have ‘main’ as the default branch.
=> BLD: Rename default branch

CHANGELOG.md, pelita/__init__.py
I looked up all old tags (minus the -rc versions) and made some quick tests and guesses of what was introduced. Obviously, there is a lot missing in between which may or may not be filled out eventually. :)
Closes #457
=> DOC: Adding a changelog file and going to 2.1.0-rc1

pelita/scripts/pelita_main.py
=> ENH: Reduce noise when module is not found.

pelita/layout.py, pelita/team.py, pelita/utils.py, test/test_layout.py, test/test_team.py
=> Walls and homezone are tuples

.github/workflows/build_docs.yml, .github/workflows/pypi_release.yml, .github/workflows/test_pytest.yml, build-docs.sh
For unclear reasons, `git shortlog` did not work in the CI environment. It needs to be `git shortlog HEAD`.
=> Something is broken with the contributors list

.github/workflows/build_docs.yml, .github/workflows/pypi_release.yml, .github/workflows/test_pytest.yml
Fixes a deprecation warning about node 16
=> BLD: Update CI dependencies

CHANGELOG.md, pelita/__init__.py
Will be merged and tagged as rc after #777
=> BLD: 2.4.0-rc1

pelita/game.py, pelita/team.py, pelita/utils.py, test/test_network.py, test/test_team.py
The test could use some more creativity.
Closes #797
=> Expose team_time in Bot

.github/workflows/test_pytest.yml, contrib/ci.cfg, contrib/ci_engine.py, contrib/test_ci_engine.py, pelita/scripts/pelita_player.py, pelita/tournament/__init__.py, pyproject.toml
Work in progress. I’ve slightly modernised it but there is a big problem currently with the hashing of the modules that needs to be fixed.
=> Refactoring of ci_engine

pelita/scripts/pelita_server.py
=> BF: Include port in server scan

pelita/game.py, pelita/scripts/pelita_main.py, pelita/scripts/pelita_tkviewer.py, pelita/ui/tk_canvas.py, pelita/ui/tk_viewer.py
add a --fullscreen CLI option and the "f" keyboard shortcut in TK to make the game window fullscreen
=> Add a CLI option to run the pelita window in fullscreen

CHANGELOG.md, pelita/__init__.py
- Food ageing and relocation to discourage camping strategies
- New attribute bot.shaded_food
- Fullscreen mode added to UI
- Enhanced CI engine
- New and enlarged collection of layouts
- New attribute bot.team_time in bot
- Add send queue to server to avoid stalling
- Fewer failures in Github CI
=> BLD: v2.5.0

CHANGELOG.md, pelita/__init__.py
- 1000 new layouts with dead ends
- A match will be played on a maze with dead ends/chambers with 25% chance
- Reduced the radius of the food shadow
- Streamlined handling of random numbers and seeding
=> BLD: Prepare v2.5.1

pelita/ui/tk_canvas.py
=> Show grid labels on all sides

pelita/utils.py, test/test_utils.py
=> RF: run_background_game does not support passing food/bots

CHANGELOG.md, pelita/__init__.py
Please add to Changelog what changed. :)
=> TODO: BLD: v2.5.2-rc1

pelita/team.py
=> Restrict `bot.say` argument to a short ASCII alphanumeric string

pelita/tournament/knockout_mode.py, test/test_tournament.py
Before:
```
1 ┐                
├─ ??? ┐         
4 ┘      │  ┏━━━━━┓
├──┨ ??? ┃
2 ┐      │  ┗━━━━━┛
├─ ??? ┘         
3 ┘                
1 ┐                       
├─ ??? ┐                
2 ┘      ├─ ??? ┐         
│      │  ┏━━━━━┓
3 ───────┘      ├──┨ ??? ┃
│  ┗━━━━━┛
4 ──────────────┘         
```
After:
```
1 ┐                
├─ ??? ┐         
4 ┘      │  ┏━━━━━┓
├──┨ ??? ┃
2 ┐      │  ┗━━━━━┛
├─ ??? ┘         
3 ┘                
1 ───────┐                
├─ ??? ┐         
2 ┐      │      │  ┏━━━━━┓
├─ ??? ┘      ├──┨ ??? ┃
3 ┘             │  ┗━━━━━┛
│         
4 ──────────────┘         
```
Our prior matching algorithm would only match the best agains the worst, 2nd best against 2nd worst, etc (with an exception in case of an odd number of teams) but it did not take care how …
=> Distribute the teams better in the knock-out bracket

pelita/ui/tk_canvas.py
By request for users with tiling window managers (and I guess WMs with window snapping too).
The whole layout could try to adapt a little in some of these cases but I think this can be left for some distant future.
Maybe we should have a toggle shortcut in case someone does not like this behaviour. Is there any letter that is classically used for this?
=> ENH: Calculate additional padding for square grid cells
